[package]
name = "refer"
version = "0.2.0"
authors = ["Kruno Tomola Fabro"]
edition = "2021"
publish = false
description = "A foundational library for building graphs out of structs"
keywords = ["graph", "container", "reference", "management"]
categories = ["data-structures", "memory-management"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/ktff/refer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
bitvec = "1.0.1"
static_assertions = "1.1.0"
modular-bitfield = "0.11.2"
getset = "0.1.2"

[dev-dependencies]
rand = "*"

[features]
default = ["base_u64"]
base_u64 = []
base_u128 = []